// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-VJIobbp7JWMhbc-FifU6lLZEYxm-2ac',
    appId: '1:896880883525:web:dcc927d91df3427aaf302c',
    messagingSenderId: '896880883525',
    projectId: 'lookup-c936d',
    authDomain: 'lookup-c936d.firebaseapp.com',
    storageBucket: 'lookup-c936d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHr5GKSg7f90L3akEkQozbDxAvoQKfUU',
    appId: '1:896880883525:android:e5818d2193ec4955af302c',
    messagingSenderId: '896880883525',
    projectId: 'lookup-c936d',
    storageBucket: 'lookup-c936d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2t8jtB2_21CY3IxnWBZmJS9oxHZPDVk',
    appId: '1:896880883525:ios:6df07f719271a1cfaf302c',
    messagingSenderId: '896880883525',
    projectId: 'lookup-c936d',
    storageBucket: 'lookup-c936d.appspot.com',
    iosBundleId: 'com.example.look',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2t8jtB2_21CY3IxnWBZmJS9oxHZPDVk',
    appId: '1:896880883525:ios:69a48f4342befd25af302c',
    messagingSenderId: '896880883525',
    projectId: 'lookup-c936d',
    storageBucket: 'lookup-c936d.appspot.com',
    iosBundleId: 'com.example.look.RunnerTests',
  );
}
